name: Basic Workflow

on:
  push:
    branches:
      - basico-workflow

jobs:
  do-things:
    name: Do Things
    runs-on: ubuntu-latest

    steps:
      - name: Logrado
        run: echo "Logrado"
